### ISSUE TITLE
Bottom side of `PrimitiveBox` drawing incorrectly

### ISSUE THREAD

**Issue by kyubxy** [peipacut/Yasai#4]
The bottom side of boxes have a 1 pixel high bump in the middle.

![image](https://user-images.githubusercontent.com/28855597/136396181-a4777d0a-1082-44b2-b7c1-8005b5ddd54b.png)

This problem is more easily noticeable in smaller boxes like the ones in KeyboardTest but are still present in all primitive boxes. Only occurs when the box isn't filled. Probably an issue with some incorrect rotation values or the way information is being passed to the SDL function which draws the box.

**Comment by caveguy427** [comment]
i didnt track the inheritance of `PrimitiveBox` in an easy way, for no reason
though i dont think `PrimitiveBox` has a member for rotation
