### ISSUE TITLE
Implementation of `LoadAll` method in `ContentCache`

### ISSUE THREAD

**Issue by kyubxy** [peipacut/Yasai#5]
Currently the `LoadAll` method in `ContentCache` returns a NotImplementedException. This method should use the preexisting `LoadResource` method to load all resources in the asset root directory.

Any reasonable implementation will do.

**Comment by caveguy427** [comment]
ive made a new pull request that also includes commits for another issue
though i should probably add more checks for that other issue first
https://github.com/EpicTofuu/Yasai/pull/7
