### ISSUE TITLE
DllNotFoundException for "libSDL2.so" and etc

### ISSUE THREAD

**Issue by caveguy427** [peipacut/Yasai#8]
at least for debian, ive found that the package `libsdl2-dev` provides `libSDL2.so` by:
`apt-file search libSDL2.so`
i thought asking the user simply to install such packages would make sense to others in our case (it doesnt for me lol)
but i realized sdl packages have (similar?) `-dev` dependencies that require 30mb of storage space

thoughts?

**Comment by caveguy427** [comment]
although it is not .net core or sdl2-cs, but i was testing around stuff with linking c programs
somehow passing `-lSDL2_ttf` to gcc, the compiled executable seems linked to `libSDL2_ttf-2.0.so.0` instead

ive tried making my own test library and linking to a symlink of that library
but it doesnt seem to be directly linked like the sdl test program
`TestProgram (exec) -> TestLib.so (symlink) -> TestLib-Real.so (so file)`

ive used `ldd` to check to which `.so` files seem linked
im saying these in case it gives any clue?

**Comment by caveguy427** [comment]
if we dont want the users to be downloading some dev packages, then these are details of what we could do:
in sdl2-cs, in each file there is a string variable with the lib file's name, being used on all `DllImport`s
i think in mono or something, somehow this name gets replaced depending on the platform being ran under (`app.config`)
but in .net core this isnt happening
i dont trust myself on deciding on others' stuff, so a clue on what to do would be appreciated

to be honest i do feel this isnt much to get all of my focus, but you can guess who i am
giving me details of other stuff to do (especially examples of any bit) help me more to change focus (its fine)

**Comment by peipacut** [comment]
With the eventual move away from SDL and towards OpenTK, I don't think this issue is necessary anymore. Really appreciate the help though, a shame we can't use any of it.
